.PANTALLA00:

				ret

.PANTALLA12:

				ld		ix,RELACION_TILES_B_PANTALLA_12
				jp		.PINTURA_GLOBAL

.PANTALLA13:

				ld		ix,RELACION_TILES_B_PANTALLA_13
				jp		.PINTURA_GLOBAL

.PANTALLA14:

				ld		ix,RELACION_TILES_B_PANTALLA_14
				jp		.PINTURA_GLOBAL

.PANTALLA15:

				ld		ix,RELACION_TILES_B_PANTALLA_15
				jp		.PINTURA_GLOBAL

.PANTALLA19:

				ld		ix,RELACION_TILES_B_PANTALLA_19
				jp		.PINTURA_GLOBAL

.PANTALLA20:

				ld		ix,RELACION_TILES_B_PANTALLA_20
				jp		.PINTURA_GLOBAL

.PANTALLA21:

				ld		ix,RELACION_TILES_B_PANTALLA_21
				jp		.PINTURA_GLOBAL

.PANTALLA22:

				ld		ix,RELACION_TILES_B_PANTALLA_22
				jp		.PINTURA_GLOBAL

.PANTALLA23:

				ld		ix,RELACION_TILES_B_PANTALLA_23
				jp		.PINTURA_GLOBAL

.PANTALLA24:

				ld		ix,RELACION_TILES_B_PANTALLA_24
				jp		.PINTURA_GLOBAL

.PANTALLA27:

				ld		ix,RELACION_TILES_B_PANTALLA_27
				jp		.PINTURA_GLOBAL

.PANTALLA28:

				ld		ix,RELACION_TILES_B_PANTALLA_28
				jp		.PINTURA_GLOBAL

.PANTALLA29:

				ld		ix,RELACION_TILES_B_PANTALLA_29
				jp		.PINTURA_GLOBAL

.PANTALLA35:

				ld		ix,RELACION_TILES_B_PANTALLA_35
				jp		.PINTURA_GLOBAL

.PANTALLA42:

				ld		ix,RELACION_TILES_B_PANTALLA_42
				jp		.PINTURA_GLOBAL

.PANTALLA51:

				ld		ix,RELACION_TILES_B_PANTALLA_51
				jp		.PINTURA_GLOBAL

.PANTALLA52:

				ld		ix,RELACION_TILES_B_PANTALLA_52
				jp		.PINTURA_GLOBAL

.PANTALLA55:

				ld		ix,RELACION_TILES_B_PANTALLA_55
				jp		.PINTURA_GLOBAL

.PANTALLA64:

				ld		ix,RELACION_TILES_B_PANTALLA_64
				jp		.PINTURA_GLOBAL

.PANTALLA66:

				ld		ix,RELACION_TILES_B_PANTALLA_66
				jp		.PINTURA_GLOBAL

.PANTALLA69:

				ld		ix,RELACION_TILES_B_PANTALLA_69
				jp		.PINTURA_GLOBAL